export const ACTION_SIGN_IN = 'signIn'
export const ACTION_SIGN_UP = 'signUp'
export const ACTION_SIGN_OUT = 'signOut'
export const ACTION_TO_SIGN_IN = 'toSignIn'
export const ACTION_TO_SIGN_UP = 'toSignUp'
export const ACTION_TO_NEW = 'new'
export const ACTION_TO_PENDING = 'pending'
export const ACTION_TO_PROGRESS = 'progress'
export const ACTION_TO_COMPLETED = 'completed'

export const ROUTE_SIGN_IN = '/sign-in'
export const ROUTE_SIGN_UP = '/sign-up'
export const ROUTE_LANDING = '/'
export const ROUTE_HOME = '/home'
export const ROUTE_NEW = '/new'
export const ROUTE_PENDING = '/pending'
export const ROUTE_PROGRESS = '/progress'
export const ROUTE_COMPLETED = '/completed'